all:
	g++ -o init init.cpp
	g++ -o client 01-client.cpp
	g++ -o server 01-server.cpp
	g++ -o listingclient 02-listingclient.cpp
	g++ -o listingserver 02-listingserver.cpp
	g++ -o disk-client 03-disk-client.cpp
	g++ -o random-disk-client 03-random-client.cpp
	g++ -o disk-server 03-disk-server.cpp
	g++ -o file-sys-server 04-file-server.cpp
	g++ -o master-client 05-master-client.cpp